# --- Sample dataset

# --- !Ups

select nextval('accesorio_seq');
select nextval('agenda_seq');
select nextval('agenda_accesorio_seq');
select nextval('agenda_cancelacion_seq');
select nextval('agenda_cuenta_rol_seq');
select nextval('agenda_equipo_seq');
select nextval('agenda_formato_entrega_seq');
select nextval('agenda_ing_admon_eqpo_seq');
select nextval('agenda_ingesta_seq');
select nextval('agenda_ingesta_almacenamiento_seq');
select nextval('agenda_ingesta_det_audio_seq');
select nextval('agenda_ingesta_det_video_seq');
select nextval('agenda_ingesta_fto_seq');
select nextval('agenda_ingesta_fto_o_seq');
select nextval('agenda_ingesta_fto_s_seq');
select nextval('agenda_ingesta_idioma_seq');
select nextval('agenda_ingesta_idioma_otro_seq');
select nextval('agenda_ingesta_observacion_seq');
select nextval('agenda_ingesta_problema_seq');
select nextval('agenda_junta_seq');
select nextval('agenda_locacion_seq');
select nextval('agenda_operador_sala_seq');
select nextval('agenda_previo_autoriza_accesorio_seq');
select nextval('agenda_previo_autoriza_equipo_seq');
select nextval('agenda_sala_seq');
select nextval('agenda_sala_uso_cabina_seq');
select nextval('agenda_salida_seq');
select nextval('agenda_vehiculo_seq');
select nextval('ambito_seq');
select nextval('cola_correos_seq');
select nextval('ctacorreo_seq');
select nextval('cuenta_seq');
select nextval('cuenta_rol_seq');
select nextval('equipo_seq');
select nextval('estado_seq');
select nextval('estado_equipo_accesorio_vehiculo_seq');
select nextval('estado_material_seq');
select nextval('fase_seq');
select nextval('folio_seq');
select nextval('folio_productor_asignado_seq');
select nextval('formato_seq');
select nextval('formato_ingesta_seq');
select nextval('idioma_seq');
select nextval('medio_almacenamiento_seq');
select nextval('motivo_cancelacion_seq');
select nextval('oficio_seq');
select nextval('oficio_contacto_seq');
select nextval('oficio_contacto_correo_seq');
select nextval('oficio_contacto_telefono_seq');
select nextval('oficio_fecha_grabacion_seq');
select nextval('oficio_imagen_seq');
select nextval('oficio_productor_solicitado_seq');
select nextval('oficio_respuesta_seq');
select nextval('oficio_servicio_solicitado_seq');
select nextval('operador_sala_seq');
select nextval('personal_seq');
select nextval('personal_avatar_seq');
select nextval('personal_cambio_horario_seq');
select nextval('personal_correo_seq');
select nextval('personal_horario_seq');
select nextval('pre_agenda_seq');
select nextval('pre_agenda_accesorio_seq');
select nextval('pre_agenda_cancelacion_seq');
select nextval('pre_agenda_equipo_seq');
select nextval('pre_agenda_formato_entrega_seq');
select nextval('pre_agenda_ing_admon_eqpo_seq');
select nextval('pre_agenda_ingesta_seq');
select nextval('pre_agenda_ingesta_almacenamiento_seq');
select nextval('pre_agenda_ingesta_fmto_salida_seq');
select nextval('pre_agenda_junta_seq');
select nextval('pre_agenda_locacion_seq');
select nextval('pre_agenda_locutor_seq');
select nextval('pre_agenda_operador_sala_seq');
select nextval('pre_agenda_rol_seq');
select nextval('pre_agenda_sala_seq');
select nextval('pre_agenda_sala_uso_cabina_seq');
select nextval('pre_agenda_salida_seq');
select nextval('pre_agenda_vehiculo_seq');
select nextval('rol_seq');
select nextval('rol_derecho_seq');
select nextval('rol_fase_seq');
select nextval('registro_acceso_seq');
select nextval('sala_seq');
select nextval('sala_mantenimiento_seq');
select nextval('servicio_seq');
select nextval('tipo_contrato_seq');
select nextval('tipo_equipo_accesorio_seq');
select nextval('tipo_mantenimiento_seq');
select nextval('unidad_responsable_seq');
select nextval('vehiculo_seq');
select nextval('his_folio_seq');

select setval('accesorio_seq', (select max(id)+1 from accesorio));
select setval('agenda_seq', (select max(id)+1 from agenda));
select setval('agenda_accesorio_seq', (select max(id)+1 from agenda_accesorio));
select setval('agenda_cancelacion_seq', (select max(id)+1 from agenda_cancelacion));
select setval('agenda_cuenta_rol_seq', (select max(id)+1 from agenda_cuenta_rol));
select setval('agenda_equipo_seq', (select max(id)+1 from agenda_equipo));
select setval('agenda_formato_entrega_seq', (select max(id)+1 from agenda_formato_entrega));
select setval('agenda_ing_admon_eqpo_seq', (select max(id)+1 from agenda_ing_admon_eqpo));
select setval('agenda_ingesta_seq', (select max(id)+1 from agenda_ingesta));
select setval('agenda_ingesta_almacenamiento_seq', (select max(id)+1 from agenda_ingesta_almacenamiento));
select setval('agenda_ingesta_det_audio_seq', (select max(id)+1 from agenda_ingesta_det_audio));
select setval('agenda_ingesta_det_video_seq', (select max(id)+1 from agenda_ingesta_det_video));
select setval('agenda_ingesta_fto_seq', (select max(id)+1 from agenda_ingesta_fto));
select setval('agenda_ingesta_fto_o_seq', (select max(id)+1 from agenda_ingesta_fto_o));
select setval('agenda_ingesta_fto_s_seq', (select max(id)+1 from agenda_ingesta_fto_s));
select setval('agenda_ingesta_idioma_seq', (select max(id)+1 from agenda_ingesta_idioma));
select setval('agenda_ingesta_idioma_otro_seq', (select max(id)+1 from agenda_ingesta_idioma_otro));
select setval('agenda_ingesta_observacion_seq', (select max(id)+1 from agenda_ingesta_observacion));
select setval('agenda_ingesta_problema_seq', (select max(id)+1 from agenda_ingesta_problema));
select setval('agenda_junta_seq', (select max(id)+1 from agenda_junta));
select setval('agenda_locacion_seq', (select max(id)+1 from agenda_locacion));
select setval('agenda_operador_sala_seq', (select max(id)+1 from agenda_operador_sala));
select setval('agenda_previo_autoriza_accesorio_seq', (select max(id)+1 from agenda_previo_autoriza_accesorio));
select setval('agenda_previo_autoriza_equipo_seq', (select max(id)+1 from agenda_previo_autoriza_equipo));
select setval('agenda_sala_seq', (select max(id)+1 from agenda_sala));
select setval('agenda_sala_uso_cabina_seq', (select max(id)+1 from agenda_sala_uso_cabina));
select setval('agenda_salida_seq', (select max(id)+1 from agenda_salida));
select setval('agenda_vehiculo_seq', (select max(id)+1 from agenda_vehiculo));
select setval('ambito_seq', (select max(id)+1 from ambito));
select setval('cola_correos_seq', (select max(id)+1 from cola_correos));
select setval('ctacorreo_seq', (select max(id)+1 from ctacorreo));
select setval('cuenta_seq', (select max(id)+1 from cuenta));
select setval('cuenta_rol_seq', (select max(id)+1 from cuenta_rol));
select setval('equipo_seq', (select max(id)+1 from equipo));
select setval('estado_seq', (select max(id)+1 from estado));
select setval('estado_equipo_accesorio_vehiculo_seq', (select max(id)+1 from estado_equipo_accesorio_vehiculo));
select setval('estado_material_seq', (select max(id)+1 from estado_material));
select setval('fase_seq', (select max(id)+1 from fase));
select setval('folio_seq', (select max(id)+1 from folio));
select setval('folio_productor_asignado_seq', (select max(id)+1 from folio_productor_asignado));
select setval('formato_seq', (select max(id)+1 from formato));
select setval('formato_ingesta_seq', (select max(id)+1 from formato_ingesta));
select setval('idioma_seq', (select max(id)+1 from idioma));
select setval('medio_almacenamiento_seq', (select max(id)+1 from medio_almacenamiento));
select setval('motivo_cancelacion_seq', (select max(id)+1 from motivo_cancelacion));
select setval('oficio_seq', (select max(id)+1 from oficio));
select setval('oficio_contacto_seq', (select max(id)+1 from oficio_contacto));
select setval('oficio_contacto_correo_seq', (select max(id)+1 from oficio_contacto_correo));
select setval('oficio_contacto_telefono_seq', (select max(id)+1 from oficio_contacto_telefono));
select setval('oficio_fecha_grabacion_seq', (select max(id)+1 from oficio_fecha_grabacion));
select setval('oficio_imagen_seq', (select max(id)+1 from oficio_imagen));
select setval('oficio_productor_solicitado_seq', (select max(id)+1 from oficio_productor_solicitado));
select setval('oficio_respuesta_seq', (select max(id)+1 from oficio_respuesta));
select setval('oficio_servicio_solicitado_seq', (select max(id)+1 from oficio_servicio_solicitado));
select setval('operador_sala_seq', (select max(id)+1 from operador_sala));
select setval('personal_seq', (select max(id)+1 from personal));
select setval('personal_avatar_seq', (select max(id)+1 from personal_avatar));
select setval('personal_cambio_horario_seq', (select max(id)+1 from personal_cambio_horario));
select setval('personal_correo_seq', (select max(id)+1 from personal_correo));
select setval('personal_horario_seq', (select max(id)+1 from personal_horario));
select setval('pre_agenda_seq', (select max(id)+1 from pre_agenda));
select setval('pre_agenda_accesorio_seq', (select max(id)+1 from pre_agenda_accesorio));
select setval('pre_agenda_cancelacion_seq', (select max(id)+1 from pre_agenda_cancelacion));
select setval('pre_agenda_equipo_seq', (select max(id)+1 from pre_agenda_equipo));
select setval('pre_agenda_formato_entrega_seq', (select max(id)+1 from pre_agenda_formato_entrega));
select setval('pre_agenda_ing_admon_eqpo_seq', (select max(id)+1 from pre_agenda_ing_admon_eqpo));
select setval('pre_agenda_ingesta_seq', (select max(id)+1 from pre_agenda_ingesta));
select setval('pre_agenda_ingesta_almacenamiento_seq', (select max(id)+1 from pre_agenda_ingesta_almacenamiento));
select setval('pre_agenda_ingesta_fmto_salida_seq', (select max(id)+1 from pre_agenda_ingesta_fmto_salida));
select setval('pre_agenda_junta_seq', (select max(id)+1 from pre_agenda_junta));
select setval('pre_agenda_locacion_seq', (select max(id)+1 from pre_agenda_locacion));
select setval('pre_agenda_locutor_seq', (select max(id)+1 from pre_agenda_locutor));
select setval('pre_agenda_operador_sala_seq', (select max(id)+1 from pre_agenda_operador_sala));
select setval('pre_agenda_rol_seq', (select max(id)+1 from pre_agenda_rol));
select setval('pre_agenda_sala_seq', (select max(id)+1 from pre_agenda_sala));
select setval('pre_agenda_sala_uso_cabina_seq', (select max(id)+1 from pre_agenda_sala_uso_cabina));
select setval('pre_agenda_salida_seq', (select max(id)+1 from pre_agenda_salida));
select setval('pre_agenda_vehiculo_seq', (select max(id)+1 from pre_agenda_vehiculo));
select setval('rol_seq', (select max(id)+1 from rol));
select setval('rol_derecho_seq', (select max(id)+1 from rol_derecho));
select setval('rol_fase_seq', (select max(id)+1 from rol_fase));
select setval('sala_seq', (select max(id)+1 from sala));
select setval('sala_mantenimiento_seq', (select max(id)+1 from sala_mantenimiento));
select setval('servicio_seq', (select max(id)+1 from servicio));
select setval('tipo_contrato_seq', (select max(id)+1 from tipo_contrato));
select setval('tipo_equipo_accesorio_seq', (select max(id)+1 from tipo_equipo_accesorio));
select setval('tipo_mantenimiento_seq', (select max(id)+1 from tipo_mantenimiento));
select setval('unidad_responsable_seq', (select max(id)+1 from unidad_responsable));
select setval('vehiculo_seq', (select max(id)+1 from vehiculo));
select setval('his_folio_seq', (select max(id)+1 from his_folio));
# --- !Downs
